apiVersion: v1
kind: Service
metadata:
  name: {{ include "mimir-single.fullname" . }}
  labels:
    {{- include "mimir-single.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: web
      name: web
    - name: http
      port: 9095
      targetPort: 9095
    - name: grpc
      port: 9195
      targetPort: 9195
    - name: ingester
      port: 9094
      targetPort: 9094
    - name: memberlist
      port: 7946
      targetPort: 7946
  selector:
    {{- include "mimir-single.selectorLabels" . | nindent 4 }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ include "mimir-single.fullname" . }}-headless
  labels:
    {{- include "mimir-single.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: web
      name: web
    - name: http
      port: 9095
      targetPort: 9095
    - name: grpc
      port: 9195
      targetPort: 9195
    - name: ingester
      port: 9094
      targetPort: 9094
    - name: memberlist
      port: 7946
      targetPort: 7946
  selector:
    {{- include "mimir-single.selectorLabels" . | nindent 4 }}
  clusterIP: None
  publishNotReadyAddresses: true