name: Building

on:
  workflow_call:
    outputs:
      version:
        description: version created on this build
        value: ${{ jobs.build.outputs.version }}
    secrets:
      DOCKER_REGISTRY:
        description: Docker registry URL
        required: true
      DOCKER_USERNAME:
        description: Docker username
        required: true
      DOCKER_PASSWORD:
        description: Docker password
        required: true
      DOCKER_REPOSITORY:
        description: Docker repository name
        required: true

jobs:
  versioning:
    uses: Ziul/swagger-operator/blob/main/.github/workflows/version.yaml@main
    with:
      runner: ubuntu-latest

  build-helm:
    name: Helm Build & Publish to GitHub Pages
    runs-on: ubuntu-latest
    needs: [versioning]
    if: github.ref_name == 'main' || github.event_name == 'release' || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Package Helm chart
        run: |
          helm package . \
            --app-version ${{ needs.versioning.outputs.MajorMinorPatch }} \
            --version ${{ needs.versioning.outputs.MajorMinorPatch }}
          mkdir -p helm-charts
          mv ${{ github.event.repository.name }}-*.tgz helm-charts/

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy new chart to gh-pages
        run: |
          cp helm-charts/*.tgz gh-pages/
          cp README.md gh-pages/
          cd gh-pages
          helm repo index . --url https://ziul.github.io/${{ github.event.repository.name }}/

      - name: Commit and push changes
        run: |
          cd gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update Helm chart [skip ci]" || echo "No changes to commit"
          git push origin gh-pages
